const emojis = [
  {emojis: ['🦶', '⚽'], answer: 'football'},
  {emojis: ['🚗', '💨'], answer: 'fast car'},
  {emojis: ['🌧️', '☂️'], answer: 'rainy day'},
  {emojis: ['🍎', '📱'], answer: 'apple phone'},
  {emojis: ['🎬', '🍿'], answer: 'movie night'},
  {emojis: ['🐱', '👀'], answer: 'cat eyes'},
  {emojis: ['🐍', '🔫'], answer: 'snake shot'},
  {emojis: ['🍕', '❤️'], answer: 'love pizza'},
  {emojis: ['🎮', '👦'], answer: 'gamer boy'},
  {emojis: ['📚', '🎓'], answer: 'study time'},
  {emojis: ['🎤', '🎶'], answer: 'singing'},
  {emojis: ['🦷', '🪥'], answer: 'brush teeth'},
  {emojis: ['💻', '☕'], answer: 'coding'},
  {emojis: ['🏀', '⛹️'], answer: 'basketball'},
  {emojis: ['👰', '🤵'], answer: 'wedding'},
  {emojis: ['🎁', '🎉'], answer: 'birthday'},
  {emojis: ['🚀', '🌕'], answer: 'moon mission'},
  {emojis: ['🛌', '💤'], answer: 'sleeping'},
  {emojis: ['🐶', '🐾'], answer: 'dog walk'},
  {emojis: ['🍿', '📺'], answer: 'movie time'},
  {emojis: ['🕷️', '🕸️'], answer: 'spider web'},
  {emojis: ['🏝️', '🌞'], answer: 'island vacation'},
  {emojis: ['💡', '🤔'], answer: 'bright idea'},
  {emojis: ['🎯', '🏹'], answer: 'target'},
  {emojis: ['🎃', '👻'], answer: 'halloween'},
  {emojis: ['🎅', '🎄'], answer: 'christmas'},
  {emojis: ['💣', '🔥'], answer: 'explosion'},
  {emojis: ['🧊', '🥶'], answer: 'cold ice'},
  {emojis: ['📸', '😎'], answer: 'photo shoot'},
  {emojis: ['🚿', '🧼'], answer: 'shower time'},
  {emojis: ['🌮', '🌯'], answer: 'mexican food'},
  {emojis: ['📞', '👂'], answer: 'phone call'},
  {emojis: ['🧑‍🍳', '🍝'], answer: 'cook pasta'},
  {emojis: ['🐔', '🥚'], answer: 'chicken egg'},
  {emojis: ['🕶️', '🌞'], answer: 'sun glasses'},
  {emojis: ['🏃', '💨'], answer: 'running fast'},
  {emojis: ['🌈', '☀️'], answer: 'sun after rain'},
  {emojis: ['📦', '📬'], answer: 'mail delivery'},
  {emojis: ['🏥', '🩺'], answer: 'hospital'},
  {emojis: ['👶', '🍼'], answer: 'baby bottle'},
  {emojis: ['🧛', '🩸'], answer: 'vampire'},
  {emojis: ['🚴', '🏁'], answer: 'bike race'},
  {emojis: ['🕵️', '🔍'], answer: 'detective'},
  {emojis: ['🏄', '🌊'], answer: 'surfing'},
  {emojis: ['🪂', '🗻'], answer: 'sky diving'},
  {emojis: ['🧟', '💀'], answer: 'zombie'},
  {emojis: ['🧙', '✨'], answer: 'wizard magic'},
  {emojis: ['🧠', '📘'], answer: 'brain power'},
  {emojis: ['🐷', '💤'], answer: 'lazy pig'},
];

export default emojis;
