const charades = [
  'Bird',
  'Washing dishes',
  'Playing guitar',
  'Drinking tea',
  'Swimming',
  'Walking a dog',
  'Typing on keyboard',
  'Driving a car',
  'Sneezing',
  'Cooking',
  'Skiing',
  'Reading a book',
  'Brushing teeth',
  'Flying a plane',
  'Painting a wall',
  'Climbing a tree',
  'Singing',
  'Playing basketball',
  'Sleeping',
  'Opening a door',
  'Fishing',
  'Running',
  'Lifting weights',
  'Taking a photo',
  'Playing video games',
  'Jumping rope',
  'Blowing a balloon',
  'Dancing',
  'Shopping',
  'Eating noodles',
  'Petting a cat',
  'Wearing glasses',
  'Playing piano',
  'Crying',
  'Laughing',
  'Yoga',
  'Meditating',
  'Calling someone',
  'Brushing hair',
  'Making a sandwich',
  'Tying shoelaces',
  'Cleaning window',
  'Looking through binoculars',
  'Shaving beard',
  'Opening an umbrella',
  'Holding a baby',
  'Taking a shower',
  'Riding a bicycle',
  'Drawing on paper',
  'Shooting an arrow',
  'Paddling a canoe',
  'Ironing clothes',
  'Stretching',
  'Bouncing a ball',
  'Writing a letter',
  'Feeding a baby',
  'Watering plants',
  'Pumping a tire',
];

export default charades;
