const topics = [
  'Famous People',
  'Car Brands',
  'Football Teams',
  'Fruits',
  'Countries',
  'Superheroes',
  'Cartoon Characters',
  'Professions',
  'Movies',
  'TV Shows',
  'Animals',
  'Musical Instruments',
  'Drinks',
  'Clothing Brands',
  'Apps & Websites',
  'Sports',
  'Languages',
  'School Subjects',
  'Countries Capitals',
  'Cities',
  'Flowers',
  'Vegetables',
  'Furniture',
  'Jobs',
  'Video Games',
  'Technology Brands',
  'Food Dishes',
  'Desserts',
  'Board Games',
  'Social Media Influencers',
  'Youtubers',
  'Actors',
  'Actresses',
  'Singers',
  'Rappers',
  'Books',
  'Authors',
  'Holidays',
  'Sports Equipment',
  'Space Stuff',
  'Planets',
  'Insects',
  'Tools',
  'Kitchen Items',
  'Body Parts',
  'Colors',
  'Shapes',
  'Sea Creatures',
  'Birds',
  'Vehicles',
  'Camping Items',
  'Toys',
  'Hobbies',
  'Clothing Items',
  'School Supplies',
  'Fairy Tale Characters',
  'Mythological Creatures',
  'Dinosaurs',
  'Currencies',
  'Inventions',
];

export default topics;
